[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Information on the package
[project]
name = "FAST_AEP"
description = "A python implementation for AEP and gradients efficient and fast computation"
version = "0.1"
authors = [
    {name = "DTU Wind Energy"}
]
dependencies = [
    "numpy",
    "autograd",
    "scipy",
    "matplotlib",
    "pandas",
    "py_wake",    
    "gpytorch",
    "torch",
    "topfarm"
]
